spring:
  application:
    name: CosmoCatsMarketplace

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cosmo}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
        hibernate:
          jdbc.time_zone: UTC
          jdbc.batch_size: 15
          order_inserts: true
          order_updates: true
          query.fail_on_pagination_over_collection_fetch: true
          query.in_clause_parameter_padding: true
          connection.provider_disables_autocommit: true

  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog.yml